### ISSUE TITLE
Status of `get_HMDHFD`

### ISSUE THREAD

**Issue by maraab23** [IvanWilli/DemoKin#21]
This is rather a question instead of an issue: I noticed that you moved `get_HMDHFD` from the */R* folder to the */dev* folder. Is there a reason for this? The function seems to work correctly for me, and I appreciated it for conveniently getting data into R.

**Comment by IvanWilli** [comment]
We decided to not maintain that function because parent package [HMDHFDplus ](https://twitter.com/timriffe1/status/1621582398872846336) had to update because of HMD and HFD changes, and in the meantime (some months) our function started to failed. We´ll see in the future if comes back, but please use it. I think it can have another arguments like sex ("male", "female", "both") and others.
